// Generated by https://gstudio.io/pages/undefined

import { Component, Input, Output, EventEmitter  } from '@angular/core';
import {MatDialog, MatDialogRef, MAT_DIALOG_DATA} from '@angular/material/dialog';

@Component({
    selector: 'dialogmaterialangular',
    templateUrl: './dialogmaterialangular.component.html',
    styleUrls: ['./dialogmaterialangular.component.css']
})
export class Dialogmaterialangular {
    
}