// Generated by https://gstudio.io/pages/undefined

import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Page } from './page/page.component';
import { Dialogdata } from './dialogdata/dialogdata.component';
import { Cardsection } from './cardsection/cardsection.component';
import { Card } from './card/card.component';
import { Selectmaterialangular } from './selectmaterialangular/selectmaterialangular.component';
import { Buttonmaterialangular } from './buttonmaterialangular/buttonmaterialangular.component';
import { Cardnumber } from './cardnumber/cardnumber.component';

@NgModule({
    imports: [ CommonModule ],
    declarations: [
        Page,
        Dialogdata,
        Cardsection,
        Card,
        Selectmaterialangular,
        Buttonmaterialangular,
        Cardnumber
    ],
    exports: [
        Page,
        Dialogdata,
        Cardsection,
        Card,
        Selectmaterialangular,
        Buttonmaterialangular,
        Cardnumber
    ]
})
export class gstudioModule { }