// Generated by https://gstudio.io/pages/undefined

import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Page } from "./page/page.component";
import { Dialogmaterialangular } from "./dialogmaterialangular/dialogmaterialangular.component";
import { Dialogdata } from "./dialogdata/dialogdata.component";
import { Buttonmaterialangular } from "./buttonmaterialangular/buttonmaterialangular.component";

@NgModule({
  imports: [
    CommonModule,
    ...(((window || global) as any).customImports
      ? ((window || global) as any).customImports
      : [])
  ],
  declarations: [
    Page,
    Dialogmaterialangular,
    Dialogdata,
    Buttonmaterialangular,
    ...(((window || global) as any).customDeclarations
      ? ((window || global) as any).customDeclarations
      : [])
  ],
  exports: [
    Page,
    Dialogmaterialangular,
    Dialogdata,
    Buttonmaterialangular,
    ...(((window || global) as any).customExports
      ? ((window || global) as any).customExports
      : [])
  ]
})
export class GstudioModule {}
