// Generated by https://gstudio.io/pages/undefined

import { Component, Input, Output, EventEmitter  } from '@angular/core';
import { MatSelectModule } from "@angular/material/select";

((window || global) as any).customImports =
  ((window || global) as any).customImports || [];
((window || global) as any).customImports.push(MatSelectModule);

@Component({
    selector: 'selectmaterialangular',
    templateUrl: './selectmaterialangular.component.html',
    styleUrls: ['./selectmaterialangular.component.css']
})
export class Selectmaterialangular {
    @Input() options: Array<string>;
    @Input() placeholder: string;
    @Input() value: string;
    @Output() valueChange: EventEmitter<any> = new EventEmitter();
}