// Generated by https://gstudio.io/pages/undefined

import { Component, Optional } from "@angular/core";

// Edit 3 - Obter a referência do dialog para poder fecha-lo
import { MatDialogRef } from "@angular/material/dialog";

@Component({
  selector: "dialogmaterialangular-wrapper",
  template: `
    <dialogdata
      [selectedOption]="initiallySelectedOption"
      (selectedOptionChange)="initiallySelectedOption = $event"
    ></dialogdata>

    <buttonmaterialangular
      [label]="'OK'"
      (onClick)="closeDialog()"
    ></buttonmaterialangular>
  `
})
export class DialogmaterialangularWrapper {
  public closeDialog() {
    this.dialogRef.close();
  }

  public initiallySelectedOption = "Option1";

  constructor(
    // Edit 3
    @Optional() public dialogRef: MatDialogRef<DialogmaterialangularWrapper>
  ) {}
}
