// Generated by https://gstudio.io/pages/undefined

import { Component, Input } from "@angular/core";

import { MatButtonModule } from "@angular/material/button";
((window || global) as any).customImports =
  ((window || global) as any).customImports || [];
((window || global) as any).customImports.push(MatButtonModule);

@Component({
  selector: "buttonmaterialangular",
  templateUrl: "./buttonmaterialangular.component.html",
  styleUrls: ["./buttonmaterialangular.component.css"]
})
export class Buttonmaterialangular {
  @Input() label: string;
}
