// Generated by https://gstudio.io/pages/undefined

import { Component, Optional } from "@angular/core";

import { MatDialogModule } from "@angular/material/dialog";
((window || global) as any).customImports =
  ((window || global) as any).customImports || [];
((window || global) as any).customImports.push(MatDialogModule);

@Component({
  selector: "dialogmaterialangular",
  templateUrl: "./dialogmaterialangular.component.html",
  styleUrls: ["./dialogmaterialangular.component.css"]
})
export class Dialogmaterialangular {}
