// Generated by https://gstudio.io/pages/undefined

import { Component, Input, Output, EventEmitter  } from '@angular/core';
import { MatDialogModule } from "@angular/material/dialog";

((window || global) as any).customImports =
  ((window || global) as any).customImports || [];
((window || global) as any).customImports.push(MatDialogModule);

@Component({
    selector: 'dialogdata',
    templateUrl: './dialogdata.component.html',
    styleUrls: ['./dialogdata.component.css']
})
export class Dialogdata {
    @Input() selectedOption: string;
    @Output() selectedOptionChange: EventEmitter<any> = new EventEmitter();
    
    get_WyJPcHRpb24xIiwgIk9wdGlvbjIiLCAiT3B0aW9uMyJd() {
        return ["Option1", "Option2", "Option3"];
    }
    
    handle_dGhpcy5zZWxlY3RlZE9wdGlvbkNoYW5nZS5uZXh0KCRldmVudCk($event) {
        this.selectedOptionChange.next($event)
    }
}