// Generated by https://gstudio.io/pages/undefined

import { Component } from "@angular/core";

@Component({
  selector: "dialogdata",
  templateUrl: "./dialogdata.component.html",
  styleUrls: ["./dialogdata.component.css"]
})
export class Dialogdata {}
