// Generated by https://gstudio.io/pages/undefined

import { Component, Input, Output, EventEmitter } from '@angular/core';


@Component({
    selector: 'buttonmaterialangular',
    templateUrl: './buttonmaterialangular.component.html',
    styleUrls: ['./buttonmaterialangular.component.css']
})
export class Buttonmaterialangular {
    @Input() label: string;
    @Output() click: EventEmitter<any> = new EventEmitter();
}