// Generated by https://gstudio.io/pages/undefined

import { Component, Input, Output, EventEmitter  } from '@angular/core';


@Component({
    selector: 'card',
    templateUrl: './card.component.html',
    styleUrls: ['./card.component.css']
})
export class Card {
    @Input() img_src: string;
    @Input() text: string;
}