// Generated by https://gstudio.io/pages/undefined

import { Component, Input, Output, EventEmitter } from '@angular/core';


@Component({
    selector: 'cardsection',
    templateUrl: './cardsection.component.html',
    styleUrls: ['./cardsection.component.css']
})
export class Cardsection {
    
}