// Generated by https://gstudio.io/pages/undefined

import { Component, Optional } from "@angular/core";

// Edit 3 - Obter a referência do dialog para poder fecha-lo
import { MatDialogRef } from "@angular/material/dialog";

@Component({
  selector: "dialogmaterialangular-wrapper",
  template: `
    <dialogmaterialangular></dialogmaterialangular>
    <buttonmaterialangular
      [label]="'OK'"
      (click)="closeDialog()"
    ></buttonmaterialangular>
  `
})
export class DialogmaterialangularWrapper {
  public closeDialog() {
    this.dialogRef.close();
  }

  constructor(
    // Edit 3
    @Optional() public dialogRef: MatDialogRef<DialogmaterialangularWrapper>
  ) {}
}
