// Generated by https://gstudio.io/pages/undefined

import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Page } from './page/page.component';
import { Dialogmaterialangular } from './dialogmaterialangular/dialogmaterialangular.component';
import { Dialogdata } from './dialogdata/dialogdata.component';
import { Cardsection } from './cardsection/cardsection.component';
import { Buttonmaterialangular } from './buttonmaterialangular/buttonmaterialangular.component';
import { Selectbancopan } from './selectbancopan/selectbancopan.component';

/** Custom imports usage example
 * Put this inside you components codePrefix:
 * import { MatButtonModule } from "@angular/material/button";
 * ((window || global) as any).customImports = ((window || global) as any).customImports || [];
 * ((window || global) as any).customImports.push(MatButtonModule);
 * */

@NgModule({
    imports: [
        ...(((window || global) as any).customImports ? ((window || global) as any).customImports : []),
        CommonModule
    ],
    declarations: [
        ...(((window || global) as any).customDeclarations ? ((window || global) as any).customDeclarations : []),
        Page,
        Dialogmaterialangular,
        Dialogdata,
        Cardsection,
        Buttonmaterialangular,
        Selectbancopan
    ],
    exports: [
        ...(((window || global) as any).customExports ? ((window || global) as any).customExports : []),
        Page,
        Dialogmaterialangular,
        Dialogdata,
        Cardsection,
        Buttonmaterialangular,
        Selectbancopan,
    ]
})
export class gstudioModule { }