// Generated by https://gstudio.io/pages/undefined

import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Page } from './page/page.component';
import { Dialogmaterialangular } from './dialogmaterialangular/dialogmaterialangular.component';
import { Dialogdata } from './dialogdata/dialogdata.component';
import { Cardsection } from './cardsection/cardsection.component';
import { Buttonmaterialangular } from './buttonmaterialangular/buttonmaterialangular.component';
import { Selectbancopan } from './selectbancopan/selectbancopan.component';

@NgModule({
    imports: [ CommonModule ],
    declarations: [
        Page,
        Dialogmaterialangular,
        Dialogdata,
        Cardsection,
        Buttonmaterialangular,
        Selectbancopan
    ],
    exports: [
        Page,
        Dialogmaterialangular,
        Dialogdata,
        Cardsection,
        Buttonmaterialangular,
        Selectbancopan
    ]
})
export class gstudioModule { }