// Generated by https://gstudio.io/pages/undefined

import { Component, Input, Output, EventEmitter  } from '@angular/core';


@Component({
    selector: 'cardnumber',
    templateUrl: './cardnumber.component.html',
    styleUrls: ['./cardnumber.component.css']
})
export class Cardnumber {
    @Input() text: string;
}