// Generated by https://gstudio.io/pages/undefined

import { Component, Input, Output, EventEmitter  } from '@angular/core';


@Component({
    selector: 'page',
    templateUrl: './page.component.html',
    styleUrls: ['./page.component.css']
})
export class Page {
    @Output() tapSimulateNow: EventEmitter<any> = new EventEmitter();
    
    handle_JGV2ZW50LnN0b3BQcm9wYWdhdGlvbigpOwpvcGVuRGlhbG9nKCk($event) {
        $event.stopPropagation();
        openDialog()
    }
    
    handle_dGhpcy50YXBTaW11bGF0ZU5vdy5uZXh0KCRldmVudCk($event) {
        this.tapSimulateNow.next($event)
    }
}